import { createContext, useState, useContext } from 'react';

// Create the LanguageContext
const LanguageContext = createContext();

// Create a custom hook to easily access the language context
export const useLanguage = () => useContext(LanguageContext);

// Language strings for English and Hindi
const languageStrings = {
  en: {
    logo: 'Kisaan-Konnect',
    home: 'Home',
    about: 'About Us',
    services: 'Services',
    awareness: 'Awareness',
    marketPlace: 'Market Place',
    contactUs: 'Contact us',
    email: 'Email: support@kisaankonnect.com',
    login: 'LOGIN',
    english: 'English',
    hindi: 'Hindi',
    footerAbout: 'Empowering farmers through technology.',
    welcome: 'Welcome to',
    onestop: 'The One Stop Solution',
    herodescription: 'A platform that connects farmers to the world and provides them with the best solutions to help them with their farming needs.',
    largeImageAlt: 'Large agriculture scene',
    smallImageAlt: 'Small agriculture scene',
    introductionTitle: 'About Kisaan Konnect',
    introductionMainTitle: 'Empowering Farmers & Promoting Sustainable Agriculture',
    introductionSubtitle: 'Kisaan Konnect is your gateway to modern farming solutions.',
    introductionDescription: 'We are committed to connecting farmers with the latest innovations in sustainable farming, organic products, and agricultural support. Whether you\'re looking to boost productivity, access financial subsidies, or connect with markets, Kisaan Konnect is here to help.',
    featureOne: 'Cutting-edge AI technology designed to forecast the best path for your future!',
    featureTwo: 'Stay updated with the latest news and insights shaping the future of agriculture!',
    benefitOne: '✔ Access to the latest agricultural technologies and market insights.',
    benefitTwo: '✔ Dedicated support for small and large-scale farmers alike.',
    cropDiseaseTitle: 'Crop Disease Prediction',
    cropDiseaseDescription: 'Predict potential crop diseases early to prevent crop loss and increase yield.',
    whatCropTitle: 'What Crop to Grow',
    whatCropDescription: 'Get recommendations on the best crops to grow based on soil, weather, and market demand.',
    fertilizerPredictionTitle: 'Fertilizer Prediction',
    fertilizerPredictionDescription: 'Receive personalized fertilizer recommendations to optimize crop growth and reduce costs.',
    serviceIntroText: 'Our Services',
    whatWeOffer: 'What We Offer',
    benefitOne1: 'Increased efficiency in farming practices',
    benefitTwo2: 'Data-driven decisions to enhance yield',
    benefitThree: 'Personalized recommendations tailored to your needs',
    benefitFour: 'Cost-effective solutions to reduce waste and optimize resources',
    latestNewsHeading: 'Latest News in Agriculture',
    newsOneTitle: 'New Agricultural Reforms Announced',
    newsOneDescription: 'The government has introduced new reforms that aim to support small farmers and boost productivity.',
    newsTwoTitle: 'Weather Patterns Affecting Crop Yield',
    newsTwoDescription: 'Farmers are urged to adopt more climate-resilient crops as weather patterns become more erratic.',
    newsThreeTitle: 'Organic Farming on the Rise',
    newsThreeDescription: 'A growing number of farmers are switching to organic farming, leading to increased demand for organic produce.',
    newsFourTitle: 'Farmers Receive New Subsidy',
    newsFourDescription: 'Subsidies have been increased for farmers in rural areas, providing much-needed financial support.',
    footer_about_text: "Empowering farmers through technology. Stay updated with the latest agricultural trends, organic farming tips and cutting-edge innovations in sustainable farming.",
    footer_explore_heading: "Explore",
    footer_about_us: "About Us",
    footer_our_services: "Our Services",
    footer_latest_news: "Latest News",
    footer_market_place: "Market Place",
    footer_recent_news_heading: "Recent News",
    footer_recent_news1: "Innovations in Sustainable Farming",
    footer_recent_news2: "Organic Farming Tips for Beginners",
    footer_contact_heading: "Contact",
    footer_phone: "9943-455-644",
    footer_email: "support@kisaanconnect.com",
    footer_address: "Dwarka, India",
    footer_rights_reserved: "All Rights Reserved.",
    footer_developers: "Developers",
    footer_github: "GitHub",
    cdp_heading: "Crop Disease Prediction",
    cdp_subhead: "Upload an image and get predictions",
    cdp_dropzone: "Drag n drop an image here, or click to attach a file",
    cdp_uploaded: "Uploaded Image:",
    cdp_loading: "Loading...",
    cdp_predicted: "Predicted Class: ",
    wctg_heading: 'What Crop to Grow',
    wctg_description: 'Fill in the details to get Crop recommendations',
    wctg_nitrogen: 'Nitrogen (N)',
    wctg_phosphorous: 'Phosphorous (P)',
    wctg_potassium: 'Potassium (K)',
    wctg_temperature: 'Temperature (°C)',
    wctg_humidity: 'Humidity (%)',
    wctg_ph: 'pH Level',
    wctg_rainfall: 'Rainfall (mm)',
    wctg_predicting: 'Predicting...',
    wctg_predict: 'Predict',
    wctg_result: 'Recommended Crop:',
    wctg_error: 'Failed to get prediction',
    wctg_image_alt: 'What Crop to Grow',
    fp_heading: 'Fertilizer Prediction',
    fp_description: 'Fill in the details to get fertilizer recommendations',
    fp_temperature: 'Temperature (°C)',
    fp_humidity: 'Humidity (%)',
    fp_moisture: 'Moisture (%)',
    fp_soil_type: 'Soil Type',
    fp_crop_type: 'Crop Type',
    fp_select_soil_type: 'Select Soil Type',
    fp_select_crop_type: 'Select Crop Type',
    fp_nitrogen: 'Nitrogen Content (mg/kg)',
    fp_potassium: 'Potassium Content (mg/kg)',
    fp_phosphorous: 'Phosphorous Content (mg/kg)',
    fp_loading: 'Loading...',
    fp_get_recommendation: 'Get Fertilizer Recommendation',
    fp_recommended: 'Recommended Fertilizer:',
    fp_error: 'Failed to get prediction',
    fp_image_alt: 'Fertilizer Prediction',
  },
  hi: {
    logo: 'किसान कनेक्ट',
    home: 'मुखपृष्ठ',
    about: 'हमारे बारे में',
    services: 'सेवाएं',
    awareness: 'जागरूकता',
    marketPlace: 'बाजार स्थान',
    contactUs: 'संपर्क करें',
    email: 'ईमेल: support@kisaankonnect.com',
    login: 'लॉग इन',
    english: 'अंग्रेजी',
    hindi: 'हिंदी',
    footerAbout: 'तकनीक के माध्यम से किसानों को सशक्त बनाना।',
    welcome: 'स्वागत है',
    onestop: 'एक ही स्थान पर समाधान',
    largeImageAlt: 'बड़ी कृषि दृश्य',
    smallImageAlt: 'छोटी कृषि दृश्य',
    introductionTitle: 'किसान कनेक्ट के बारे में',
    introductionMainTitle: 'किसानों को सशक्त बनाना और स्थायी कृषि को बढ़ावा देना',
    introductionSubtitle: 'किसान कनेक्ट आधुनिक कृषि समाधानों का आपका गेटवे है।',
    introductionDescription: 'हम सतत कृषि, जैविक उत्पादों और कृषि समर्थन में नवीनतम नवाचारों के साथ किसानों को जोड़ने के लिए प्रतिबद्ध हैं। चाहे आप उत्पादकता बढ़ाने, वित्तीय सब्सिडी प्राप्त करने, या बाजारों से जुड़ने की कोशिश कर रहे हों, किसान कनेक्ट आपकी सहायता के लिए यहां है।',
    featureOne: 'आपके भविष्य के लिए सबसे अच्छा रास्ता पूर्वानुमान करने के लिए डिज़ाइन की गई अत्याधुनिक एआई तकनीक!',
    featureTwo: 'कृषि के भविष्य को आकार देने वाली नवीनतम खबरों और अंतर्दृष्टियों से अवगत रहें!',
    benefitOne: '✔ नवीनतम कृषि तकनीकों और बाजार अंतर्दृष्टियों तक पहुंच।',
    benefitTwo: '✔ छोटे और बड़े पैमाने पर किसानों के लिए समर्पित समर्थन।',  
    herodescription: 'एक प्लेटफॉर्म जो किसानों को दुनिया से जोड़ता है और उन्हें उनकी खेती की आवश्यकताओं में मदद करने के लिए सबसे अच्छी समाधान प्रदान करता है।',
    cropDiseaseTitle: 'फसल रोग भविष्यवाणी',
    cropDiseaseDescription: 'फसल की हानि को रोकने और उपज बढ़ाने के लिए प्रारंभिक फसल रोगों का पूर्वानुमान लगाएं।',
    whatCropTitle: 'कौन सी फसल उगाएं',
    whatCropDescription: 'मिट्टी, मौसम और बाजार की मांग के आधार पर उगाने के लिए सबसे अच्छी फसलों की सिफारिशें प्राप्त करें।',
    fertilizerPredictionTitle: 'उर्वरक भविष्यवाणी',
    fertilizerPredictionDescription: 'फसल वृद्धि को अनुकूलित करने और लागत को कम करने के लिए व्यक्तिगत उर्वरक अनुशंसाएं प्राप्त करें।',
    serviceIntroText: 'हमारी सेवाएं',
    whatWeOffer: 'हम क्या प्रदान करते हैं',
    benefitOne1: 'खेती के तरीकों में दक्षता में वृद्धि',
    benefitTwo2: 'उपज बढ़ाने के लिए डेटा-संचालित निर्णय',
    benefitThree: 'आपकी आवश्यकताओं के लिए अनुकूलित व्यक्तिगत अनुशंसाएं',
    benefitFour: 'अपशिष्ट को कम करने और संसाधनों को अनुकूलित करने के लिए लागत प्रभावी समाधान',
    latestNewsHeading: 'कृषि में नवीनतम समाचार',
    newsOneTitle: 'नई कृषि सुधारों की घोषणा',
    newsOneDescription: 'सरकार ने छोटे किसानों का समर्थन करने और उत्पादकता बढ़ाने के लिए नए सुधार पेश किए हैं।',
    newsTwoTitle: 'मौसम के पैटर्न से फसल की पैदावार प्रभावित',
    newsTwoDescription: 'किसानों को अधिक जलवायु-प्रतिरोधी फसलों को अपनाने के लिए प्रोत्साहित किया जा रहा है क्योंकि मौसम के पैटर्न अधिक अनियमित हो रहे हैं।',
    newsThreeTitle: 'जैविक खेती बढ़ रही है',
    newsThreeDescription: 'किसानों की एक बढ़ती संख्या जैविक खेती की ओर बढ़ रही है, जिससे जैविक उत्पादों की मांग बढ़ रही है।',
    newsFourTitle: 'किसानों को नई सब्सिडी मिली',
    newsFourDescription: 'ग्रामीण क्षेत्रों के किसानों के लिए सब्सिडी बढ़ा दी गई है, जिससे बहुत जरूरी वित्तीय सहायता मिली है।',
    footer_about_text: "तकनीक के माध्यम से किसानों को सशक्त बनाना। नवीनतम कृषि रुझानों, जैविक खेती युक्तियों और सतत खेती में नवाचारों में अपडेट रहें।",
    footer_explore_heading: "अन्वेषण",
    footer_about_us: "हमारे बारे में",
    footer_our_services: "हमारी सेवाएं",
    footer_latest_news: "नवीनतम समाचार",
    footer_market_place: "बाजार स्थान",
    footer_recent_news_heading: "हाल की खबरें",
    footer_recent_news1: "सतत खेती में नवाचार",
    footer_recent_news2: "शुरुआत करने वालों के लिए जैविक खेती के टिप्स",
    footer_contact_heading: "संपर्क",
    footer_phone: "9943-455-644",
    footer_email: "support@kisaankonnect.com",
    footer_address: "द्वारका, भारत",
    footer_rights_reserved: "सभी अधिकार सुरक्षित हैं।",
    footer_developers: "डेवलपर्स",
    footer_github: "गिटहब",
    cdp_heading: "फसल रोग भविष्यवाणी",
    cdp_subhead: "एक छवि अपलोड करें और भविष्यवाणियाँ प्राप्त करें",
    cdp_dropzone: "एक छवि यहाँ खींचें और छोड़ें, या फ़ाइल जोड़ने के लिए क्लिक करें",
    cdp_uploaded: "अपलोड की गई छवि:",
    cdp_loading: "लोड हो रहा है...",
    cdp_predicted: "पूर्वानुमानित वर्ग: ",
    wctg_heading: 'कौन सी फसल उगाएं',
    wctg_description: 'फसल की सिफारिशें प्राप्त करने के लिए विवरण भरें',
    wctg_nitrogen: 'नाइट्रोजन (N)',
    wctg_phosphorous: 'फॉस्फोरस (P)',
    wctg_potassium: 'पोटैशियम (K)',
    wctg_temperature: 'तापमान (°C)',
    wctg_humidity: 'आर्द्रता (%)',
    wctg_ph: 'पीएच स्तर',
    wctg_rainfall: 'वर्षा (मिमी)',
    wctg_predicting: 'पूर्वानुमान कर रहा है...',
    wctg_predict: 'पूर्वानुमान करें',
    wctg_result: 'अनुशंसित फसल:',
    wctg_error: 'पूर्वानुमान प्राप्त करने में विफल रहा',
    wctg_image_alt: 'कौन सी फसल उगाएं',
    fp_heading: 'उर्वरक भविष्यवाणी',
    fp_description: 'उर्वरक अनुशंसाएँ प्राप्त करने के लिए विवरण भरें',
    fp_temperature: 'तापमान (°C)',
    fp_humidity: 'नमी (%)',
    fp_moisture: 'मॉइस्चर (%)',
    fp_soil_type: 'मिट्टी का प्रकार',
    fp_crop_type: 'फसल का प्रकार',
    fp_select_soil_type: 'मिट्टी का प्रकार चुनें',
    fp_select_crop_type: 'फसल का प्रकार चुनें',
    fp_nitrogen: 'नाइट्रोजन सामग्री (mg/kg)',
    fp_potassium: 'पोटैशियम सामग्री (mg/kg)',
    fp_phosphorous: 'फॉस्फोरस सामग्री (mg/kg)',
    fp_loading: 'लोड हो रहा है...',
    fp_get_recommendation: 'उर्वरक अनुशंसा प्राप्त करें',
    fp_recommended: 'अनुशंसित उर्वरक:',
    fp_error: 'भविष्यवाणी प्राप्त करने में विफल रहा',
    fp_image_alt: 'उर्वरक भविष्यवाणी',
  },
};

// Language provider component
export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const toggleLanguage = () => {
    setLanguage((prevLanguage) => (prevLanguage === 'en' ? 'hi' : 'en'));
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, languageStrings: languageStrings[language] }}>
      {children}
    </LanguageContext.Provider>
  );
};